name: CI-CD

on:
  push:
    tags:
    branches:
  pull_request:
    branches: [ '**' ]
    types: [opened, synchronize, reopened, edited]

defaults:
  run:
    working-directory: src

jobs:
  test:
    name: ğŸ›  Build, ğŸ§ª Test
    runs-on: ubuntu-latest
    
    steps:
      - name: ğŸ›’ Checkout
        uses: actions/checkout@v2

      - name: ğŸŸ£ Setup .NET 6.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: ğŸŒ´ dotnet restore
        run: dotnet restore

      - name: ğŸ›  dotnet build
        run: dotnet build --configuration Release --no-restore

      - name: ğŸ§ª dotnet test
        run: dotnet test --configuration Release --no-restore

  version:
    name: 1ï¸âƒ£2ï¸âƒ£3ï¸âƒ£ VERSION from tag
    runs-on: ubuntu-latest
    outputs:
      success: ${{ steps.get-version.outputs.success }}
      version: ${{ steps.get-version.outputs.version }}
    steps:
      - name: ğŸ›’ Checkout
        uses: actions/checkout@v2

      - name: 1ï¸âƒ£2ï¸âƒ£3ï¸âƒ£ Get VERSION
        id: get-version
        uses: ./.github/actions/version

  publish:
    name: ğŸ“¦ Publish to NuGet
    runs-on: ubuntu-latest
    needs: 
      - test
      - version
    if: needs.test.result == 'success' && needs.version.outputs.success == 'true'

    steps:
      - name: ğŸ›’ Checkout
        uses: actions/checkout@v2
      
      - name: ğŸŸ£ Setup .NET 6.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: ğŸ“¦ Pack ğŸš€ Push
        uses: ./.github/actions/nuget
        with:
          working-directory: src
          api-key: ${{ secrets.NUGET_API_KEY }}
          version: ${{ needs.version.outputs.version }}
