name: CI-CD

on:
  push:
    tags: [ "[0-9]+.[0-9]+.[0-9]+" ]
    branches: [ '**' ] 
  pull_request:
    branches: [ '**' ]
    types: [opened, synchronize, reopened, edited]

defaults:
  run:
    working-directory: src

jobs:
  test:
    name: ğŸ›  Build, ğŸ§ª Test
    runs-on: ubuntu-latest
    
    steps:
      - name: ğŸ›’ Checkout
        uses: actions/checkout@v2

      - name: ğŸŸ£ Setup .NET Core 5.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - name: ğŸŒ´ dotnet restore
        run: dotnet restore

      - name: ğŸ›  dotnet build
        run: dotnet build --configuration Release --no-restore

      - name: ğŸ§ª dotnet test
        run: dotnet test --configuration Release --no-restore

  publish:
    name: ğŸ“¦ Publish to NuGet
    runs-on: ubuntu-latest
    needs: test
    if: startsWith(github.ref, 'refs/tags/') && needs.test.result == 'success'

    steps:
      - name: ğŸ›’ Checkout
        uses: actions/checkout@v2
      
      - name: 1ï¸âƒ£2ï¸âƒ£3ï¸âƒ£ Set VERSION
        uses: ./.github/actions/version

      - name: ğŸŸ£ Setup .NET Core 5.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - name: ğŸ“¦ Pack
        run: dotnet pack --configuration Release -p:Version=$VERSION

      - name: ğŸš€ Push
        run: dotnet nuget push **.nupkg -k $NUGET_API_KEY -s https://api.nuget.org/v3/index.json --skip-duplicate
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
